table:
  name: key_values
  schema: public
select_permissions:
  - role: public
    permission:
      columns:
        - created_at
        - updated_at
        - key
        - value
      filter: {}
