import { describe, it, expect } from 'vitest';
import { pbMatcher } from '.';

describe('pbMatcher', () => {
  it('attachment', () => {
    expect(Array.from('![[sample.png]]'.matchAll(pbMatcher.attachment))[0][1]).toBe('sample.png');
    expect(Array.from('![[sample.png|200]]'.matchAll(pbMatcher.attachment))[0][2]).toBe('200');
    expect(Array.from('![[sample.jpg]]'.matchAll(pbMatcher.attachment))[0][1]).toBe('sample.jpg');
    expect(Array.from('![[sample.jpg|200]]'.matchAll(pbMatcher.attachment))[0][2]).toBe('200');
    expect(Array.from('![[sample.gif]]'.matchAll(pbMatcher.attachment))[0][1]).toBe('sample.gif');
    expect(Array.from('![[sample.gif|200]]'.matchAll(pbMatcher.attachment))[0][2]).toBe('200');
    expect(Array.from('![[sample.webp]]'.matchAll(pbMatcher.attachment))[0][1]).toBe('sample.webp');
    expect(Array.from('![[sample.webp|200]]'.matchAll(pbMatcher.attachment))[0][2]).toBe('200');
    expect(Array.from('![[sample.mp3]]'.matchAll(pbMatcher.attachment))[0][1]).toBe('sample.mp3');
    expect(Array.from('![[sample.mp4]]'.matchAll(pbMatcher.attachment))[0][1]).toBe('sample.mp4');
    expect(Array.from('![[sample.mp4|200]]'.matchAll(pbMatcher.attachment))[0][2]).toBe('200');
    expect(Array.from('![[sample.pdf]]'.matchAll(pbMatcher.attachment))[0][1]).toBe('sample.pdf');
    expect(Array.from('![[sample]]'.matchAll(pbMatcher.attachment))[0]).toBeUndefined();
    expect(Array.from('[[sample]]'.matchAll(pbMatcher.attachment))[0]).toBeUndefined();
  });
  it('image', () => {
    expect(Array.from('![[sample.png]]'.matchAll(pbMatcher.image))[0][1]).toBe('sample.png');
    expect(Array.from('![[sample.png|200]]'.matchAll(pbMatcher.image))[0][2]).toBe('200');
    expect(Array.from('![[sample.jpg]]'.matchAll(pbMatcher.image))[0][1]).toBe('sample.jpg');
    expect(Array.from('![[sample.jpg|200]]'.matchAll(pbMatcher.image))[0][2]).toBe('200');
    expect(Array.from('![[sample.gif]]'.matchAll(pbMatcher.image))[0][1]).toBe('sample.gif');
    expect(Array.from('![[sample.gif|200]]'.matchAll(pbMatcher.image))[0][2]).toBe('200');
    expect(Array.from('![[sample.webp]]'.matchAll(pbMatcher.image))[0][1]).toBe('sample.webp');
    expect(Array.from('![[sample.webp|200]]'.matchAll(pbMatcher.image))[0][2]).toBe('200');
    expect(Array.from('![[sample.mp3]]'.matchAll(pbMatcher.image))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp4]]'.matchAll(pbMatcher.image))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp4|200]]'.matchAll(pbMatcher.image))[0]).toBeUndefined();
    expect(Array.from('![[sample.pdf]]'.matchAll(pbMatcher.image))[0]).toBeUndefined();
    expect(Array.from('![[sample]]'.matchAll(pbMatcher.image))[0]).toBeUndefined();
    expect(Array.from('[[sample]]'.matchAll(pbMatcher.image))[0]).toBeUndefined();
  });
  it('sound', () => {
    expect(Array.from('![[sample.png]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.png|200]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.jpg]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.jpg|200]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.gif]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.gif|200]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.webp]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.webp|200]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp3]]'.matchAll(pbMatcher.sound))[0][1]).toBe('sample.mp3');
    expect(Array.from('![[sample.mp4]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp4|200]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample.pdf]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('![[sample]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
    expect(Array.from('[[sample]]'.matchAll(pbMatcher.sound))[0]).toBeUndefined();
  });
  it('video', () => {
    expect(Array.from('![[sample.png]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.png|200]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.jpg]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.jpg|200]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.gif]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.gif|200]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.webp]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.webp|200]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp3]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp4]]'.matchAll(pbMatcher.video))[0][1]).toBe('sample.mp4');
    expect(Array.from('![[sample.mp4|200]]'.matchAll(pbMatcher.video))[0][2]).toBe('200');
    expect(Array.from('![[sample.pdf]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('![[sample]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
    expect(Array.from('[[sample]]'.matchAll(pbMatcher.video))[0]).toBeUndefined();
  });
  it('pdf', () => {
    expect(Array.from('![[sample.png]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.png|200]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.jpg]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.jpg|200]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.gif]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.gif|200]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.webp]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.webp|200]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp3]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp4]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp4|200]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('![[sample.pdf]]'.matchAll(pbMatcher.pdf))[0][1]).toBe('sample.pdf');
    expect(Array.from('![[sample]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
    expect(Array.from('[[sample]]'.matchAll(pbMatcher.pdf))[0]).toBeUndefined();
  });
  it('md', () => {
    expect(Array.from('![[sample.png]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.png|200]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.jpg]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.jpg|200]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.gif]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.gif|200]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.webp]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.webp|200]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp3]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp4]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.mp4|200]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample.pdf]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('![[sample]]'.matchAll(pbMatcher.md))[0]).toBeUndefined();
    expect(Array.from('[[sample]]'.matchAll(pbMatcher.md))[0][1]).toBe('sample');
  });
});
